/*

AUTORES : 
            FRANCISCO JOSE MUÑOZ NAVARRO
            ALEJANDRO MUÑOZ NAVARRO

*/
package CodigoIntermedio;

public enum Operador {
    MULT, DIV, SUMA, RESTA, MAYORQUE, MENORQUE, MAYORIGU,
    MENORIGU, IGUALES, NIGUALES, OR, AND, GOTO, SKIP, ASIG, IN, OUT, RTN, PMB, CALL, PARAM, DESPLAZAR_BITS,
    IND_VAL, IND_ASG
};
